services:
  # The Semantic Layer (Connected to Neon DB)
  cube:
    image: cubejs/cube:latest
    container_name: sql_agent_cube
    ports:
      - "4000:4000" 
      - "3000:3000"
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: ${POSTGRES_HOST}
      CUBEJS_DB_NAME: ${POSTGRES_DB}
      CUBEJS_DB_USER: ${POSTGRES_USER}
      CUBEJS_DB_PASS: ${POSTGRES_PASSWORD}
      CUBEJS_DB_PORT: ${POSTGRES_PORT}
      CUBEJS_DB_SSL: "true"
      CUBEJS_DEV_MODE: ${CUBEJS_DEV_MODE}
    volumes:
      - ./cube/model:/cube/conf/model